# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg?color_snake=black&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
